#spring.jpa.database=POSTGRESQL
#spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/elk-spring?&serverTimezone=UTC
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.generate-ddl=true
#
#spring.datasource.username=postgres
#spring.datasource.password=root
#spring.datasource.hikari.maximum-pool-size=5
#spring.datasource.hikari.minimum-idle=3
#spring.datasource.hikari.idle-timeout=600000
#
#
#spring.jackson.deserialization.fail-on-unknown-properties=true
#spring.jackson.deserialization.fail-on-ignored-properties=true

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect